[site]
name = "sychostar"
url = "https://lihaoze-bob.github.io/notes-site/"
repository = "LiHaoze-Bob/notes-site"
branch = "main"

[[sources]]
path = "30_课程"
destination = "courses"

[[sources]]
path = "60_研究/62_技术积累"
destination = "knowledge/tech"

[[sources]]
path = "50_资源/53_Tools"
destination = "knowledge/tools"

[[sources]]
path = "60_研究/63_Reading"
destination = "reading/reading"

[[sources]]
path = "60_研究/61_Paper"
destination = "reading/paper"

[labels]
knowledge = "Tech"
"knowledge/tech" = "技术积累"
"knowledge/tools" = "Tools"
reading = "Reading"
"reading/reading" = "Reading"
"reading/paper" = "Paper"
